apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: k8r7s3yr0-dotnet-basic
  janus-idp.io/tekton: k8r7s3yr0-dotnet-basic
  backstage.io/kubernetes-id: k8r7s3yr0-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: k8r7s3yr0-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
